const GET_ALL_CATEGORIES_STARTED = 'GET_ALL_CATEGORIES_STARTED';
const GET_ALL_CATEGORIES_SUCCESS = 'GET_ALL_CATEGORIES_SUCCESS';
const DELETE_CATEGORY_STARTED = 'DELETE_CATEGORY_STARTED';
const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
const ADD_CATEGORY_STARTED = 'ADD_CATEGORY_STARTED';
const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
const UPDATE_CATEGORY_STARTED = 'UPDATE_CATEGORY_STARTED';
const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

const GET_ALL_ITEMS_STARTED = 'GET_ALL_ITEM_STARTED';
const GET_ALL_ITEMS_SUCCESS = 'GET_ALL_ITEMS_SUCCESS';
const DELETE_ITEM_STARTED = 'DELETE_ITEM_STARTED';
const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS';
const DELETE_ITEMS_BY_PARENT_ID_STARTED = 'DELETE_ITEMS_BY_PARENT_ID_STARTED';
const DELETE_ITEMS_BY_PARENT_ID_SUCCESS = 'DELETE_ITEMS_BY_PARENT_ID_SUCCESS';
const ADD_ITEM_STARTED = 'ADD_ITEM_STARTED';
const ADD_ITEM_SUCCESS ='ADD_ITEM_SUCCESS';
const UPDATE_ITEM_STARTED = 'UPDATE_ITEM_STARTED';
const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
const GET_ITEMS_BY_PARENTID_STARTED = 'GET_ITEMS_BY_PARENTID_STARTED';
const GET_ITEMS_BY_PARENTID_SUCCESS = 'GET_ITEMS_BY_PARENTID_SUCCESS';

export {
    GET_ALL_CATEGORIES_STARTED,
    GET_ALL_CATEGORIES_SUCCESS,
    DELETE_CATEGORY_STARTED,
    DELETE_CATEGORY_SUCCESS,
    ADD_CATEGORY_STARTED,
    ADD_CATEGORY_SUCCESS,
    UPDATE_CATEGORY_STARTED,
    UPDATE_CATEGORY_SUCCESS,
    GET_ALL_ITEMS_STARTED,
    GET_ALL_ITEMS_SUCCESS,
    DELETE_ITEM_STARTED,
    DELETE_ITEM_SUCCESS,
    DELETE_ITEMS_BY_PARENT_ID_STARTED,
    DELETE_ITEMS_BY_PARENT_ID_SUCCESS,
    ADD_ITEM_STARTED,
    ADD_ITEM_SUCCESS,
    UPDATE_ITEM_STARTED,
    UPDATE_ITEM_SUCCESS,
    GET_ITEMS_BY_PARENTID_STARTED,
    GET_ITEMS_BY_PARENTID_SUCCESS,
};
